import type { CorpusEdition, CorpusPackageManifest } from "../domain/corpus";

export const BIBLIA_LIVRE_COMMIT = "a315a15e9f4d01883b62206fe441d57762f126b3";
export const BIBLIA_LIVRE_VERSION = "2025.1.0";
export const BIBLIA_LIVRE_EDITION_ID = "biblia-livre-n4-2025.1.0";
export const BIBLIA_LIVRE_PACKAGE_ID = `biblia-livre-official-${BIBLIA_LIVRE_COMMIT}`;
export const BIBLIA_LIVRE_ATTRIBUTION =
  "Todas as Escrituras em português citadas são da Bíblia Livre (BLIVRE), Copyright © Diego Santos, Mario Sérgio, e Marco Teles, http://sites.google.com/site/biblialivre/ — versão 2025.1.0. Licença Creative Commons Atribuição 3.0 Brasil (http://creativecommons.org/licenses/by/3.0/br/). Reprodução permitida desde que devidamente mencionados fonte e autores. Scriptorium: conversão técnica F4 para shards JSON; o texto não foi traduzido nem alinhado por palavras.";

export const BIBLIA_LIVRE_BOOKS = {
  "gen.txt": ["genesis", "Genesis", "Gn", 1, "ot"],
  "exod.txt": ["exodus", "Exodus", "Êx", 2, "ot"],
  "lev.txt": ["leviticus", "Leviticus", "Lv", 3, "ot"],
  "num.txt": ["numbers", "Numbers", "Nm", 4, "ot"],
  "deut.txt": ["deuteronomy", "Deuteronomy", "Dt", 5, "ot"],
  "jos.txt": ["joshua", "Joshua", "Js", 6, "ot"],
  "juiz.txt": ["judges", "Judges", "Jz", 7, "ot"],
  "rute.txt": ["ruth", "Ruth", "Rt", 8, "ot"],
  "1sa.txt": ["1-samuel", "1 Samuel", "1Sm", 9, "ot"],
  "2sa.txt": ["2-samuel", "2 Samuel", "2Sm", 10, "ot"],
  "1rs.txt": ["1-kings", "1 Kings", "1Rs", 11, "ot"],
  "2rs.txt": ["2-kings", "2 Kings", "2Rs", 12, "ot"],
  "1crn.txt": ["1-chronicles", "1 Chronicles", "1Cr", 13, "ot"],
  "2crn.txt": ["2-chronicles", "2 Chronicles", "2Cr", 14, "ot"],
  "esd.txt": ["ezra", "Ezra", "Ed", 15, "ot"],
  "nee.txt": ["nehemiah", "Nehemiah", "Ne", 16, "ot"],
  "est.txt": ["esther", "Esther", "Et", 17, "ot"],
  "jo.txt": ["job", "Job", "Jó", 18, "ot"],
  "sal.txt": ["psalms", "Psalms", "Sl", 19, "ot"],
  "prov.txt": ["proverbs", "Proverbs", "Pv", 20, "ot"],
  "ecl.txt": ["ecclesiastes", "Ecclesiastes", "Ec", 21, "ot"],
  "cant.txt": ["song-of-songs", "Song of Songs", "Ct", 22, "ot"],
  "isa.txt": ["isaiah", "Isaiah", "Is", 23, "ot"],
  "jer.txt": ["jeremiah", "Jeremiah", "Jr", 24, "ot"],
  "lam.txt": ["lamentations", "Lamentations", "Lm", 25, "ot"],
  "eze.txt": ["ezekiel", "Ezekiel", "Ez", 26, "ot"],
  "dan.txt": ["daniel", "Daniel", "Dn", 27, "ot"],
  "ose.txt": ["hosea", "Hosea", "Os", 28, "ot"],
  "joel.txt": ["joel", "Joel", "Jl", 29, "ot"],
  "amos.txt": ["amos", "Amos", "Am", 30, "ot"],
  "oba.txt": ["obadiah", "Obadiah", "Ob", 31, "ot"],
  "jon.txt": ["jonah", "Jonah", "Jn", 32, "ot"],
  "miq.txt": ["micah", "Micah", "Mq", 33, "ot"],
  "naum.txt": ["nahum", "Nahum", "Na", 34, "ot"],
  "hab.txt": ["habakkuk", "Habakkuk", "Hc", 35, "ot"],
  "sof.txt": ["zephaniah", "Zephaniah", "Sf", 36, "ot"],
  "ageu.txt": ["haggai", "Haggai", "Ag", 37, "ot"],
  "zac.txt": ["zechariah", "Zechariah", "Zc", 38, "ot"],
  "mal.txt": ["malachi", "Malachi", "Ml", 39, "ot"],
  "mat.txt": ["matthew", "Matthew", "Mt", 40, "nt"],
  "mar.txt": ["mark", "Mark", "Mc", 41, "nt"],
  "luc.txt": ["luke", "Luke", "Lc", 42, "nt"],
  "joao.txt": ["john", "John", "Jo", 43, "nt"],
  "atos.txt": ["acts", "Acts", "At", 44, "nt"],
  "rom.txt": ["romans", "Romans", "Rm", 45, "nt"],
  "1cor.txt": ["1-corinthians", "1 Corinthians", "1Co", 46, "nt"],
  "2cor.txt": ["2-corinthians", "2 Corinthians", "2Co", 47, "nt"],
  "gal.txt": ["galatians", "Galatians", "Gl", 48, "nt"],
  "efes.txt": ["ephesians", "Ephesians", "Ef", 49, "nt"],
  "fil.txt": ["philippians", "Philippians", "Fp", 50, "nt"],
  "col.txt": ["colossians", "Colossians", "Cl", 51, "nt"],
  "1tes.txt": ["1-thessalonians", "1 Thessalonians", "1Ts", 52, "nt"],
  "2tes.txt": ["2-thessalonians", "2 Thessalonians", "2Ts", 53, "nt"],
  "1tim.txt": ["1-timothy", "1 Timothy", "1Tm", 54, "nt"],
  "2tim.txt": ["2-timothy", "2 Timothy", "2Tm", 55, "nt"],
  "tito.txt": ["titus", "Titus", "Tt", 56, "nt"],
  "flm.txt": ["philemon", "Philemon", "Fm", 57, "nt"],
  "heb.txt": ["hebrews", "Hebrews", "Hb", 58, "nt"],
  "tiag.txt": ["james", "James", "Tg", 59, "nt"],
  "1ped.txt": ["1-peter", "1 Peter", "1Pe", 60, "nt"],
  "2ped.txt": ["2-peter", "2 Peter", "2Pe", 61, "nt"],
  "1joao.txt": ["1-john", "1 John", "1Jo", 62, "nt"],
  "2joao.txt": ["2-john", "2 John", "2Jo", 63, "nt"],
  "3joao.txt": ["3-john", "3 John", "3Jo", 64, "nt"],
  "jud.txt": ["jude", "Jude", "Jd", 65, "nt"],
  "apo.txt": ["revelation", "Revelation", "Ap", 66, "nt"],
} as const;

export const BIBLIA_LIVRE_EDITION: CorpusEdition = {
  id: BIBLIA_LIVRE_EDITION_ID,
  corpusId: "biblia-livre",
  title: "Bíblia Livre N4, versão 2025.1.0",
  abbreviation: "BLIVRE N4",
  language: "pt-BR",
  script: "Latn",
  direction: "ltr",
  kind: "translation",
  version: BIBLIA_LIVRE_VERSION,
  revision: BIBLIA_LIVRE_COMMIT,
  releaseDate: "2025-01-12",
  licenseId: "CC-BY-3.0-BR",
};

export const BIBLIA_LIVRE_PACKAGE: CorpusPackageManifest = {
  id: BIBLIA_LIVRE_PACKAGE_ID,
  corpusId: "biblia-livre",
  editionId: BIBLIA_LIVRE_EDITION_ID,
  title: BIBLIA_LIVRE_EDITION.title,
  shortName: "BLIVRE N4",
  language: "pt-BR",
  script: "Latn",
  direction: "ltr",
  version: BIBLIA_LIVRE_VERSION,
  revision: BIBLIA_LIVRE_COMMIT,
  releaseDate: "2025-01-12",
  canonicalSource: "https://github.com/blivre/BibliaLivre",
  sourceRepository: "https://github.com/blivre/BibliaLivre",
  acquisitionPlan: {
    repository: "https://github.com/blivre/BibliaLivre.git",
    commitSha: BIBLIA_LIVRE_COMMIT,
    artifactRoot: "textos/f4/n4",
    artifactPattern: "*.txt",
    expectedBookIds: Object.values(BIBLIA_LIVRE_BOOKS).map((v) => v[0]),
  },
  sourceArtifactIds: [],
  format: "f4",
  versificationScheme: "biblia-livre-f4-canonical-audit",
  rights: {
    id: `rights:${BIBLIA_LIVRE_PACKAGE_ID}`,
    status: "verified",
    declaredBy: "Bíblia Livre official repository",
    declaredAtSource: `https://github.com/blivre/BibliaLivre/blob/${BIBLIA_LIVRE_COMMIT}/README.md`,
    copyrightHolder: "Diego Santos, Mario Sérgio e Marco Teles",
    license: {
      id: "CC-BY-3.0-BR",
      name: "Creative Commons Atribuição 3.0 Brasil",
      status: "open-license",
      url: "https://creativecommons.org/licenses/by/3.0/br/",
      redistributionAllowed: true,
      commercialUseAllowed: true,
      attributionRequired: true,
      attributionText: BIBLIA_LIVRE_ATTRIBUTION,
      mayStore: true,
      mayRedistribute: true,
      mayModify: true,
      mayUseCommercially: true,
      permissions: {
        redistribution: "yes",
        modification: "yes",
        commercialUse: "yes",
        shareAlike: "no",
        attribution: "yes",
      },
    },
    attribution: {
      work: "Bíblia Livre",
      authorsOrEditors: ["Diego Santos", "Mario Sérgio", "Marco Teles"],
      copyright: "Copyright © Diego Santos, Mario Sérgio, e Marco Teles",
      license: "Creative Commons Atribuição 3.0 Brasil",
      canonicalSource: "https://github.com/blivre/BibliaLivre",
      requiredText: BIBLIA_LIVRE_ATTRIBUTION,
    },
    evidence: ["README.md", "LICENCA.md"].map((path, i) => ({
      id: `evidence:blivre:${i}`,
      sourceUrl: `https://github.com/blivre/BibliaLivre/blob/${BIBLIA_LIVRE_COMMIT}/${path}`,
      sourceKind: i ? ("corpus-rights-file" as const) : ("official-repository" as const),
      observedAt: "2026-09-06T03:00:00.000Z",
      licenseId: "CC-BY-3.0-BR",
    })),
  },
  provenance: {
    acquisition: "editorial",
    creationMethod: "human",
    packageId: BIBLIA_LIVRE_PACKAGE_ID,
    sourceArtifactIds: [],
    attribution: BIBLIA_LIVRE_ATTRIBUTION,
  },
  contentCapabilities: ["verse-text", "footnotes", "headings"],
  integrity: { requiredAlgorithm: "SHA-256", status: "not-verified", verifiedArtifactIds: [] },
  status: "ready-for-import",
};
